# Generated by Django 3.0.5 on 2020-04-21 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_status', models.BooleanField()),
                ('time_stamp', models.IntegerField()),
                ('name', models.TextField()),
                ('label', models.SlugField(unique=True)),
                ('dj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_song_id', models.CharField(blank=True, max_length=500, null=True)),
                ('artist', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('associated_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song_queue', to='player.Room')),
                ('room_song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_song', to='player.Room')),
            ],
        ),
    ]
