# Generated by Django 3.0.5 on 2020-04-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200422_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Profile'),
        ),
    ]
