# Generated by Django 3.0.5 on 2020-04-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_stamp',
            field=models.IntegerField(null=True),
        ),
    ]
