# Generated by Django 3.0.5 on 2020-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200422_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dj',
            field=models.IntegerField(default=0),
        ),
    ]
