# Generated by Django 3.0.2 on 2020-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200422_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dj',
            field=models.TextField(),
        ),
    ]
