# Generated by Django 3.0.2 on 2020-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200423_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(to='player.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
