# Generated by Django 3.0.2 on 2020-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20200425_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='spotify_username',
            new_name='spotify_display_name',
        ),
    ]
